const ADVISORS = [
  { slug: "michelle-herrera", name: "Michelle Herrera", school: "Pomona College", major: "Undecided", role: "Senior Advising Director" },
  { slug: "juan-paulino", name: "Juan Paulino", school: "University of Wisconsin-Madison", major: "Electrical Engineering", role: "Advising Fellow" },
  { slug: "loraine-ramirez-santana", name: "Loraine Ramirez-Santana", school: "Brown University", major: "Public Health and Latin American & Caribbean Studies", role: "Advising Fellow" },
  { slug: "caden-reedy", name: "Caden Reedy", school: "University of North Carolina Chapel Hill", major: "Public Health and Computer Science", role: "Advising Fellow" },
  { slug: "kendall-zakari", name: "Kendall Zakari", school: "Boston University", major: "Chemistry", role: "Advising Fellow" },
  { slug: "michael-adikah", name: "Michael Adikah", school: "Trinity College", major: "Philosophy & History", role: "Advising Fellow" },
  { slug: "eldana-arega", name: "Eldana Arega", school: "Columbia University", major: "Neuroscience", role: "Advising Fellow" },
  { slug: "marie-babisa", name: "Marie Babisa", school: "Cornell University", major: "Applied Economics & Management", role: "Advising Fellow" },
  { slug: "jordon-echevarria", name: "Jordon Echevarria", school: "Swarthmore College", major: "Educational Policy", role: "Advising Fellow" },
  { slug: "asal-al-shammari", name: "Asal Al Shammari", school: "Rice University", major: "Pre-Med", role: "Advising Fellow" },
  { slug: "akaribe-jatto", name: "Akaribe Jatto", school: "Brown University", major: "Undeclared", role: "Advising Fellow" },
  { slug: "justin-martinez", name: "Justin Martinez", school: "Harvard College", major: "History & Literature and Economics", role: "Advising Fellow" },
  { slug: "joshua-lee", name: "Joshua Lee", school: "Amherst College", major: "Jurisprudence and Political Science & Philosophy", role: "Advising Fellow" },
  { slug: "clara-senada", name: "Clara Senada", school: "Yale University", major: "Neuroscience", role: "Advising Fellow" },
  { slug: "shyam-manjanath", name: "Shyam Manjanath", school: "Duke University", major: "Undeclared", role: "Advising Fellow" },
  { slug: "joseph-beato", name: "Joseph Beato", school: "Rice University", major: "Sports Medicine & Exercise Science", role: "Advising Fellow" },
  { slug: "agnes-osazuwa", name: "Agnes Osazuwa", school: "Northeastern University", major: "Pharmaceutical Sciences", role: "Advising Fellow" },
  { slug: "amanat-sohi", name: "Amanat Sohi", school: "Fresno State (Honors College)", major: "Biology", role: "Advising Fellow" },
  { slug: "ania-dawson", name: "Ania Dawson", school: "Yale University", major: "Ecology/Evolutionary Biology & Political Science", role: "Advising Fellow" },
  { slug: "jasmin-gavin", name: "Jasmin Gavin", school: "Tufts University", major: "Chemistry", role: "Advising Fellow" },
  { slug: "daeshanell-jarrett", name: "Daeshanell Jarrett", school: "Georgetown University", major: "Nursing", role: "Advising Fellow" },
  { slug: "mackenzie-pettiford", name: "Mackenzie Pettiford", school: "Yale University", major: "Political Science", role: "Advising Fellow" },
  { slug: "dominic-mimbang", name: "Dominic Mimbang", school: "Harvard College", major: "Social Studies / Pre-Law", role: "Advising Fellow" },
  { slug: "bryhanny-m", name: "Bryhanny M.", school: "Barnard College", major: "Pre-Dental Track", role: "Advising Fellow" },
  { slug: "joshua-oyerokun", name: "Joshua Oyerokun", school: "University of Pennsylvania", major: "Computer Science & Finance", role: "Advising Fellow" },
  { slug: "earl-coker", name: "Earl Coker", school: "University of Pennsylvania", major: "Economics", role: "Advising Fellow" },
  { slug: "emmanuel-demard", name: "Emmanuel Demard", school: "Bowdoin College", major: "Physics & Astronomy", role: "Advising Fellow" },
  { slug: "katherine-paredes-lara", name: "Katherine Paredes-Lara", school: "Princeton University", major: "Neuroscience", role: "Advising Fellow" }
];
